'use strict';var hfa={TAB:0,pl:1,Ep:2},Ju=function(){return new rb("MediaRouter.CastStreaming.Session.Launch")},Ku=function(){return new xb("MediaRouter.CastStreaming.Session.Length")},Lu=function(a){Bb("MediaRouter.CastStreaming.Start.Success",a,hfa)};var Mu=gb("mr.mirror.cast.LogUploader"),Ou=function(a,b,c){Nu("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},Nu=function(a,b,c,d){if(0==b.size)Mu.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);rt("https://clients2.google.com/cr/report",function(f){f=f.target;
var g=null;zt(f)?(g=At(f),Mu.info("Upload to Crash succeeded: "+g)):Mu.info("Upload to Crash failed. HTTP status: "+f.Xa());d&&d(g)},"POST",e,void 0,3E4)}};var Pu=function(){this.g=0;Ml(this)},Ru=function(){Qu||(Qu=new Pu);return Qu},ifa=function(){var a=Ru(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};Pu.prototype.Ia=function(){return"mirror.cast.LogUtils"};Pu.prototype.tb=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};Pu.prototype.sb=function(){var a=Kl(this);this.g=a&&a.lastAutoSubmitMillis||0};var Qu=null;gb("mr.mirror.cast.LogUtils");var Su={gA:"OFFER",Ov:"ANSWER",JA:"PRESENTATION",Kx:"GET_STATUS",WB:"STATUS_RESPONSE",Jx:"GET_CAPABILITIES",nw:"CAPABILITIES_RESPONSE",xB:"RPC"};var jfa=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},lfa=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;Tu(JSON.parse(a),function(d){b=kfa(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},kfa=function(a){var b=new jfa;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Uu(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=l(Object.keys(Su)),e=d.next();!e.done;e=d.next())if(Su[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(n(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}Tu(a.error,function(f){b.error=mfa(f)},function(){throw Error('"error" must be an Object');});Tu(a.answer,function(f){b.g=nfa(f)},function(){throw Error('"answer" must be an Object');});Tu(a.status,function(f){b.status=ofa(f)},function(){throw Error('"status" must be an Object');
});Tu(a.capabilities,function(f){b.capabilities=pfa(f)},function(){throw Error('"capabilities" must be an Object');});return b},Tu=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Uu=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Vu=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},Wu=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},qfa=function(){this.m=null;this.g=[];this.h=
[];this.j=this.l=this.D=null},nfa=function(a){var b=new qfa;Uu(a.udpPort,function(c){b.m=c},function(){throw Error('"answer.udpPort" must be a number');});Vu(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Vu(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.D=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=
String(a.castMode));return b},rfa=function(){this.details=this.description=this.code=null},mfa=function(a){var b=new rfa;Uu(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Tu(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},sfa=function(){this.h=this.g=null},ofa=function(a){var b=new sfa;Uu(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});Vu(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},tfa=function(){this.h=this.g=null},pfa=function(a){var b=new tfa;Wu(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;Tu(c,function(e){d=ufa(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},vfa=function(){this.j=this.o=this.D=this.m=this.F=this.g=this.u=this.h=this.initDataTypes=this.l=null},ufa=function(a){var b=new vfa;"keySystemName"in a&&(b.l=String(a.keySystemName));Wu(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});Wu(a.codecs,function(c){b.h=c},function(){throw Error('"capabilities.codecs" must be an array');});Wu(a.secureCodecs,function(c){b.u=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Wu(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});Wu(a.videoRobustness,function(c){b.F=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.m=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.D=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.o=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.j=String(a.distinctiveIdentifierSupport));return b};var Xu=function(a){this.s=gb("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0};Xu.prototype.subscribe=function(a,b){if(this.h.has(a))throw Error("Attempt to multiple-subscribe to the same response type: "+a);this.h.set(a,b);this.j=0;nb(this.s,"Added subscriber for "+a+"-type messages.");this.g||(this.g=bu(this.l),this.g.onMessage=this.m.bind(this))};
var Yu=function(a,b){a.h.delete(b)&&nb(a.s,function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.eb(),a.g=null)};Xu.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Zu=function(a,b,c,d,e){var f=null,g=function(){Yu(a,c);null!=f&&(clearTimeout(f),f=null)};try{a.subscribe(c,function(k){e(k)&&g()})}catch(k){e(null,k);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(k){g();e(null,k)})};
Xu.prototype.m=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=lfa(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.s.K(b):nb(this.s,b);++this.j}};var $u=function(){this.g=Promise.resolve(1)},bv=function(a,b,c){return av(a,function(d){return d==b},c)},wfa=function(a,b){var c=[3,4];return av(a,function(d){return-1!=c.indexOf(d)},b)},cv=function(a,b){a.g=a.g.catch(function(){return 1});return av(a,function(){return!0},b)},av=function(a,b,c){var d,e,f=new Promise(function(g,k){d=g;e=k});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var k=new xfa(g);try{var m=c(k)}catch(p){m=
Promise.reject(p)}return m.then(function(p){return d(p)},function(p){return e(p)}).then(function(){if(null===k.g)throw Error("A prior operation that started at "+(g+" did not complete."));return k.g})},function(g){e(g);throw g;});return f},xfa=function(a){this.h=a;this.g=null},dv=function(a,b){a.g="number"===typeof b?b:a.h};var ev=chrome.cast.streaming,gv=function(a,b,c,d,e){this.L=a.sessionId;this.F=a.vg;this.N=a.we;this.j=b;this.J=c;this.M=d;this.W=fv(e,"onAnswer",this.F);this.X=fv(e,"onSessionStop",this.F);this.s=gb("mr.mirror.cast.StreamingLaunchWorkflow");this.C=new $u;this.o=this.G=this.u=this.h=this.g=this.D=this.m=this.l=null};
gv.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof hv,f=b instanceof hv;(e&&b&&!f||f&&a&&!e)&&Gb("Mixing remoting and non-remoting tracks");return bv(this.C,1,function(g){d.l=a;d.m=b;d.D=c;d.s.info(function(){return"Launching streaming for "+iv(d)+" to a "+(d.N+".")});return yfa(d).then(d.H.bind(d)).then(function(k){return zfa(d,k).then(function(m){d.W();var p=Afa(d,m,k);d.g=jv(d,d.g,p);d.h=jv(d,d.h,p);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(k));d.G=!!m.l;d.o=function(u,A){u==d.g?d.D.wf("Audio stream (id="+u+") error: "+A):u==d.h&&d.D.wf("Video stream (id="+u+") error: "+A)};ev.rtpStream.onError.addListener(d.o);return Bfa(d,m,p)})}).then(function(){d.s.info(function(){return"Launched streaming for "+iv(d)});d.D.Ng(d);dv(g,2);return{Vq:d.g,wv:d.h}})})};
gv.prototype.stop=function(){var a=this;return cv(this.C,function(b){if(!a.l&&!a.m)return dv(b,1),Promise.resolve();a.s.info(function(){return"Stopping streaming for "+iv(a)+"."});a.o&&(ev.rtpStream.onError.removeListener(a.o),a.o=null);if(a.D){var c=a.D.Ch();a.D=null}else c=Promise.resolve();return c.then(function(){a.g&&(ev.rtpStream.stop(a.g),ev.rtpStream.destroy(a.g),a.g=null);a.h&&(ev.rtpStream.stop(a.h),ev.rtpStream.destroy(a.h),a.h=null);a.u&&(ev.udpTransport.destroy(a.u),a.u=null);a.X();a.s.info(function(){return"Stopped streaming for "+
iv(a)+"."});a.l=null;a.m=null;dv(b,1)})})};
var Cfa=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return ev.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return ev.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.s.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},Dfa=function(a){return Promise.all([a.g&&new Promise(function(b){return ev.rtpStream.getStats(a.g,b)}),
a.h&&new Promise(function(b){return ev.rtpStream.getStats(a.h,b)})]).catch(function(b){a.s.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(n(b.filter(function(c){return!!c}))))})},iv=function(a){if(a.l&&a.m)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.m)b="video-only ";else return"stopped";return a.l instanceof hv||a.m instanceof hv?b+"remoting":b+"streaming"},yfa=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(ev.rtpStream.destroy(d),d=null);e&&!a.m&&(ev.rtpStream.destroy(e),e=null);a.s.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.u=f;b()};a.l instanceof hv||a.m instanceof hv?ev.session.create(null,null,c):ev.session.create(a.l,a.m,c)})};
gv.prototype.H=function(){for(var a=Ej(),b=Ej(),c=[],d=l([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,p=l(ev.rtpStream.getSupportedParams(e)),u=p.next();!u.done;u=p.next())u=u.value,u.payload.payloadType=g,u.payload.maxLatency=this.j.maxLatencyMillis,u.payload.minLatency=this.j.minLatencyMillis,u.payload.animatedLatency=this.j.animatedLatencyMillis,u.payload.ssrc=
k,u.payload.clockRate=m,u.payload.aesKey=a,u.payload.aesIvMask=b,f?(u.payload.channels=2,u.payload.maxBitrate=this.j.audioBitrate,u.payload.maxFrameRate=100):(u.payload.minBitrate=this.j.minVideoBitrate,u.payload.maxBitrate=this.j.maxVideoBitrate,u.payload.maxFrameRate=this.j.maxFrameRate),c.push(new Efa(e,u));return c};
var jv=function(a,b,c){b&&!c.some(function(d){return d.yg==b})&&(a.s.K("Destroying RTP stream not selected by the receiver: id="+b),ev.rtpStream.destroy(b),b=null);return b},zfa=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,k={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(k.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(k)}var m=a.l instanceof hv||a.m instanceof hv?"remoting":"mirroring",p={type:"OFFER",sessionId:a.L,seqNum:Im(a.J),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.s.info(function(){return"Sending OFFER message: "+JSON.stringify(p)});Zu(a.M,p,"ANSWER",1E4,function(u,A){if(null==u)d(A);else if("ok"==u.result&&u.g){if(u.h!=p.seqNum)return a.s.K("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(u)),!1;((A=u.g.j)&&A!=m||!A&&"mirroring"!=m)&&a.s.error("Expected receiver to ANSWER with castMode="+m+", but got: "+A);nb(a.s,function(){return"Received ANSWER: "+JSON.stringify(u)});c(u.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(u)));return!0})})},Afa=function(a,b,c){if(b.g.length!=b.h.length)return a.s.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={Ff:e.Ff},++f){var g=b.g[f];if(0>g||g>=c.length)return a.s.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.Ff=c[g];if(d.some(function(k){return function(m){return m.yg==k.Ff.yg}}(e)))return a.s.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.Ff.params.payload.feedbackSsrc=b.h[g];if(d.some(function(k){return function(m){return m.params.payload.feedbackSsrc==k.Ff.params.payload.feedbackSsrc}}(e)))return a.s.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),[];d.push(e.Ff)}return d},
Bfa=function(a,b,c){var d=null,e=function(){d&&(ev.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var k=b.m||2344;a.s.info(function(){return"Starting RTP streams to receiver at "+(a.F+":"+k)+(" for selected offers: "+JSON.stringify(c))});var m=a.u||-1;a.j.dscpEnabled&&(a.s.info("Enabled DSCP in sender."),ev.udpTransport.setOptions(m,{DSCP:!0}));ev.udpTransport.setDestination(m,{address:a.F,port:k});var p=new Set(c.map(function(A){return A.yg}));d=function(A){p.delete(A);
0==p.size&&f()};ev.rtpStream.onStarted.addListener(d);m=l(c);for(var u=m.next();!u.done;u=m.next())u=u.value,ev.rtpStream.toggleLogging(u.yg,a.j.enableLogging),ev.rtpStream.start(u.yg,u.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},fv=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.s.error("Error from testHooks."+b,e)}}:function(){}},Efa=function(a,b){this.yg=a;this.params=b},hv=function(){};var kv=function(a,b,c,d,e,f){this.o=a;this.M=Ffa(b,this.o.Db);this.J=new gv(this.o.Db,c,d,e,f);this.G=e;this.m=new $u;this.j=new Gfa;this.C=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.s=gb("mr.mirror.cast.MediaRemoter");this.F=this.g=this.D=this.l=this.H=null;this.h=!0;this.u=this.L.bind(this)};
kv.prototype.initialize=function(a,b){var c=this;return bv(this.m,1,function(d){c.H=a;c.l=b;var e=c.C.createInterfacePtrAndBind();c.C.setConnectionErrorHandler(function(){c.s.info("Remoter mojo pipe connection error.");lv(c)});c.g=new mojo.MirrorServiceRemotingSourcePtr;var f=kaa(c.o.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.o.mediaSource);c.s.info("Connecting remoter to browser: tabId="+f);(Si.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,
mojo.makeRequest(c.g));c.g.ptr.setConnectionErrorHandler(function(){c.s.info("RemotingSource mojo pipe connection error.");lv(c)});return Hfa(c).then(function(){if(c.h)c.g.onSinkAvailable(c.M);dv(d,2)})})};
var lv=function(a){return cv(a.m,function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.D;a.D=null;a.l=null;a.H=null;a.C.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.u);return new Promise(function(d){window.setTimeout(function(){mv(a).then(function(){dv(b,1);d();c&&c()})},250)})})};h=kv.prototype;h.Ku=function(a){nv(this.j,a)};h.Ng=function(a){this.l&&this.l.Ng(a)};h.Ch=function(){return this.l?this.l.Ch():Promise.resolve()};
h.wf=function(a,b){this.s.error("Error during streaming: "+a,b);if(this.g)this.g.onError();lv(this)};
h.start=function(){var a=this,b=!1;this.s.info(function(){b=!0;return"Starting next media remoting session."});b&&Ifa(this.j,function(c){return a.s.info(c)});Jfa(this.j);bv(this.m,2,function(c){return(0,a.H)().then(function(d){a.D=d;a.G.subscribe("RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.D&&(++f.o,f.h+=e.length,f.D(e))}});dv(c,3)}).catch(function(d){return mv(a).then(function(){dv(c);throw d;})})}).then(function(){a.s.info("Remoting started successfully.")}).catch(function(c){a.s.error("Failed to start remoting",
c);a.g.onError()})};h.jv=function(a,b){var c=this;return bv(this.m,3,function(d){return c.J.start(a?new hv:null,b?new hv:null,c).then(function(e){Kfa(c.j,function(f){return c.G.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});dv(d,4);return{audio_stream_id:e.Vq||-1,video_stream_id:e.wv||-1}}).catch(function(e){return mv(c).then(function(){dv(d);throw e;})})}).catch(function(d){c.s.error("Failed to start remoting streams",d);lv(c);return{audio_stream_id:-1,video_stream_id:-1}})};
h.stop=function(a){var b=this;wfa(this.m,function(c){b.g.onStopped(a);return mv(b).then(function(){b.s.info("Remoting stopped.");dv(c,5);(0,b.D)().then(function(){return bv(b.m,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.M);dv(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.D=null})}).catch(function(c){b.s.error("Failed to stop remoting: ",c);lv(b)})};
h.wr=function(){null===this.F&&(this.F=sf(this.o.Db.vg).then(function(a){return a.h||!1}));return this.F.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var mv=function(a){return a.J.stop().then(function(){Yu(a.G,"RPC");Lfa(a.j);ov(a.j)})},Hfa=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.s.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.s.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,a.s.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)||chrome.settingsPrivate.onPrefsChanged.addListener(a.u);b()})})};
kv.prototype.L=function(a){if(this.g){a=l(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.s.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;this.s.info("mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.M);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var Ffa=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.fv||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,g=d.audio_capabilities,k=d.video_capabilities,m=b.we||"";(a.g||[]).forEach(function(p){switch(p){case "audio":g.push(e.CODEC_BASELINE_SET);break;case "aac":g.push(e.CODEC_AAC);break;case "opus":g.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:c.s.info("Unknown mediaCap name: "+p)}});b.we&&"Chromecast Ultra"==b.we&&k.push(f.SUPPORT_4K);return d};kv.prototype.estimateTransmissionCapacity=kv.prototype.wr;kv.prototype.stop=kv.prototype.stop;kv.prototype.startDataStreams=kv.prototype.jv;kv.prototype.start=kv.prototype.start;
kv.prototype.sendMessageToSink=kv.prototype.Ku;
var Gfa=function(){this.D=this.m=this.g=null;this.F=this.h=this.o=this.j=this.u=0;this.l=null},Jfa=function(a){a.g=[];pv(a,performance.now())},Kfa=function(a,b,c){a.m=b;a.D=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return nv(a,d.data).then(d.Mu,d.jo)})):pv(a,performance.now())},Lfa=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.jo(b)});a.g=null}a.m=null;a.D=null},nv=function(a,b){if(a.m){var c=btoa(String.fromCharCode.apply(null,b));++a.u;
a.j+=b.length;return a.m({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,Mu:d,jo:e})}):Promise.reject(Error("RPC pipe not started"))},Ifa=function(a,b){ov(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.F)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec).");pv(a,c);c=d}b(c)},3E4)},
ov=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},pv=function(a,b){a.u=0;a.j=0;a.o=0;a.h=0;a.F=b};var Mfa=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Nfa=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var qv=function(a,b,c,d,e){this.j=new gv(a,b,c,d,void 0===e?null:e);this.s=gb("mr.mirror.cast.MediaStreamer");this.m=new $u;this.l=this.h=this.g=this.D=null};qv.prototype.start=function(a,b){var c=this;return bv(this.m,1,function(d){c.D=a;c.g=Mfa(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=Nfa(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return dv(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return dv(d,2)})})};
qv.prototype.stop=function(){var a=this;return cv(this.m,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.D=null;a.l=null;dv(b,1)})})};var Ofa=function(a){return bv(a.m,2,function(b){a.s.info("Suspending media streaming...");return a.j.stop().then(function(){a.s.info("Suspended media streaming.");dv(b,3)})})};
qv.prototype.resume=function(){var a=this;return bv(this.m,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.s.info("Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){a.s.info("Resumed media streaming.");dv(b,2)})})};var rv=function(a,b,c){this.m=a;this.l=b;this.j=c;this.s=gb("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};rv.prototype.start=function(){var a=this;null==this.g&&(nb(this.s,"Starting Wifi Status Monitoring."),this.h=[],this.j.subscribe("STATUS_RESPONSE",function(b){return Pfa(a,b)}),this.g=setInterval(function(){return sv(a)},12E4),sv(this))};rv.prototype.stop=function(){null!=this.g&&(nb(this.s,"Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,Yu(this.j,"STATUS_RESPONSE"))};
var Pfa=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.s.K(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),a.s.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.s.K(function(){return"Ignoring response without status: "+JSON.stringify(b)})},sv=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.m,seqNum:Im(a.l),get_status:["wifiSnr","wifiSpeed"]})};var tv=function(a,b,c,d){this.M=b.vg;this.o={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:pj(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.we};this.H=c;this.G=d;this.l=this.h=this.u=this.D=this.m=this.F=this.j=null;this.g=[]};tv.prototype.Ng=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.F=Date.now();this.h=setInterval(this.C.bind(this,a),9E5)};
tv.prototype.Ch=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.C(this.j);this.j=null;return a}return Promise.resolve()};tv.prototype.wf=function(a,b){null==this.m&&(this.m=Date.now(),"function"===typeof a?this.D=a():"string"===typeof a&&(this.D=a),b&&"string"===typeof b.stack&&(this.u=b.stack))};
var Qfa=function(a,b){return(null==a.j?Promise.resolve():a.C(a.j)).then(function(){var c=b.map(function(d){d=uv(a,d);var e=d.map(function(g){return g.events}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.xg}).forEach(function(g,k){0<k&&f.push(",");f.push(g)});f.push("]");return{events:new Blob(e,{type:"application/gzip"}),xg:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
tv.prototype.C=function(a){var b=this;if(null!=this.l)return this.l;var c=sf(this.M).then(function(d){d={receiverVersion:d.g,receiverConnected:d.l,receiverOnEthernet:d.h,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.m};Object.assign(d,b.o);var e=Date.now();Object.assign(d,{startTime:b.F,endTime:e,activity:iv(a),receiverWifiStatus:Array.from(b.G.h)});b.F=e;null!=b.m&&(Object.assign(d,{streamingErrorTime:b.m,streamingErrorMessage:b.D,streamingErrorCause:b.u}),b.m=null,b.D=null,b.u=null);return d});
return(this.l=Promise.all([c.then(function(d){return Cfa(a,d)}),c,Dfa(a)]).then(function(d){var e=l(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({events:d,xg:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=uv(b,b.H);b.l=null}))||Promise.resolve()};
var uv=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].xg.size+1;if(0>b)break;c.push({events:null,xg:a.g[d].xg});if(null!=a.g[d].events){var e=a.g[d].events.size;b>=e&&(c[c.length-1].events=a.g[d].events,b-=e)}}return c.reverse()};var vv=gb("mr.NetworkUtils"),wv=function(a,b){if(!baa)return Promise.reject("TDLS feature not enabled.");vv.info("setTDLSState_: ip="+a+", state="+b);return new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(e){chrome.runtime.lastError?(vv.K("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(vv.info("TDLS state changed: state = "+b+", status = "+e),c(e))})})};var xv=function(a,b,c,d){d=void 0===d?null:d;mj.call(this,b);var e=b.Db;this.G=e.sessionId;this.L=e.vg;this.C=a;this.N=d;this.s=gb("mr.mirror.cast.Session");this.F=new $u;this.u=new Hm("mirror.cast.SeqNumGenerator");this.o=new Xu(b.id);this.D=new qv(e,this.C,this.u,this.o,this.N);this.m=null;this.g=new tv(a,e,c,new rv(this.G,this.u,this.o));this.l=!1;this.H=null};q(xv,mj);h=xv.prototype;
h.start=function(a){var b=this;return bv(this.F,1,function(c){var d=Ju();return Rfa(b).then(function(e){b.l=e;return b.D.start(a,b)}).then(function(){if(b.D.j.G){var e=b.g;e.o.tdlsIsOn=b.l;e.G.start();Sfa(b)}else b.g.o.tdlsIsOn=b.l;d.end();b.H=Ku();dv(c,2);return b})})};
h.stop=function(){var a=this;return cv(this.F,function(b){a.H&&(a.H.end(),a.H=null);a.g.G.stop();return a.D.stop().then(function(){return a.m?lv(a.m):Promise.resolve()}).then(function(){a.m=null;return a.l?Tfa(a):Promise.resolve()}).then(function(){a.l=!1;dv(b,4)})})};
h.ho=function(){var a=this,b={sessionId:this.G,seqNum:Im(this.u),type:"PRESENTATION",icons:[],title:naa(this.Fc)};this.s.info("Sending session metadata update to receiver: "+this.G);this.o.sendMessage(b).catch(function(c){a.s.K("Failed to send activity to sink: "+c.message)})};h.Ng=function(a){this.g.Ng(a)};h.Ch=function(){return this.g.Ch()};h.wf=function(a,b){this.g.wf(a,b);this.s.error(a,b);this.stop()};
var yv=function(a,b){return Qfa(a.g,b)},Rfa=function(a){a.s.info("maybeEnableTdls_: useTdls = "+a.C.useTdls);return a.C.useTdls?wv(a.L,!0).then(function(b){if("Connected"==b)return a.s.info("Successfully enabled TDLS."),!0;a.s.K("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.s.K("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Tfa=function(a){return wv(a.L,!1).catch(function(b){return a.s.error("Error while turning TDLS back off",b)})},Sfa=function(a){Ufa(a).then(function(b){(b.g||
[]).includes("video")?Vfa(a,b):a.s.K(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.s.K("None/Invalid capabilites response. Media Remoting disabled.",b)})},Ufa=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.G,seqNum:Im(a.u)};a.s.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Zu(a.o,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.h!=d.seqNum)return a.s.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;nb(a.s,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Vfa=function(a,b){bv(a.F,2,function(c){var d=a.h.Db.we||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.s.K('HACK: Media Remoting disabled because the receiver model--"'+(d+'" according to discovery--is not a Chromecast.')),
dv(c),Promise.resolve();a.m=new kv(a.h,b,a.C,a.u,a.o,a.N);return a.m.initialize(a.W.bind(a),a).catch(function(e){a.s.error("Media Remoting start failed: "+e.message,e)}).then(function(){return dv(c)})})};xv.prototype.W=function(){var a=this;return bv(this.F,2,function(b){return new Promise(function(c,d){Ofa(a.D).then(function(){dv(b,3);a.M=!0;hj(a);c(a.X.bind(a))}).catch(function(e){a.wf("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
xv.prototype.X=function(){var a=this;return bv(this.F,3,function(b){return new Promise(function(c,d){a.D.resume().then(function(){dv(b,2);a.M=!1;hj(a);c()}).catch(function(e){a.wf("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var zv=function(){fj.call(this,"cast_streaming");this.D=this.F=this.M=this.H=this.l=null;this.nb=this.J="";this.ea=this.u=!1;this.ja=this.xa.bind(this);this.L=this.N=this.W=this.X=this.m=null};q(zv,fj);h=zv.prototype;h.Og=function(a){this.u=a||!1;this.ea=!0};h.getName=function(){return"cast_streaming"};
h.Yj=function(a,b,c,d,e){var f=this;if(!this.u)return fj.prototype.Yj.call(this,a,b,c,d,e);this.V.info("Start mirroring on route "+a.id);if(!this.ea)return Bi(Error("Not initialized"));var g=new Promise(function(k,m){f.o().then(function(){if(aj(b)&&c.shouldCaptureVideo)return Pi(!1).then(function(p){f.nb=p})}).then(function(){return e?e(a).g:a}).then(function(p){f.J=b;Wfa(f,p);var u=f.H.createInterfacePtrAndBind(),A=f.M.createInterfacePtrAndBind(),E=Xfa(p,c);Yfa(f,p,b,d);if(!f.l)throw new Fi("Error to get mirroring service host");
f.F=new mojo.MirroringCastMessageChannelPtr;f.X=Ju();f.l.start(E,u,A,mojo.makeRequest(f.F));f.m=new mj(a,f.j.pj.bind(f.j));hj(f.m);Zfa(f,p,b);f.N=function(){return k(p)};f.L=m}).catch(function(p){f.V.info("Mirroring launch error: "+p);f.rg(p.reason);m(p)})});return Ci(g)};h.Oh=function(a,b){return new xv(a,b,20969472,null)};h.wh=function(){Lu(0)};h.th=function(){Lu(1)};h.ui=function(){Lu(2)};h.uh=function(){Ab("MediaRouter.CastStreaming.Session.End")};
h.rg=function(a){Bb("MediaRouter.CastStreaming.Start.Failure",a,Ei)};h.vh=function(){Ab("MediaRouter.CastStreaming.Stream.End")};
h.Si=function(a){var b=this;return this.u?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&ifa(),e=[9351424];d&&e.push(20969472);return yv(a,e).then(function(f){var g=f[f.length-1];f=Tl(f[0].events).catch(function(k){b.V.error("Failed to persist events Blob.",k)});d&&0<g.events.size?Ou(g.events,void 0,b.pt.bind(b)):c&&Nu("stats.json",g.xg,void 0,void 0);return f})})};h.pt=function(a){a&&(Ru().g=Date.now())};
h.Xj=function(a){if(this.u)return db();this.V.info("Received message to upload logs for "+a);return this.g?yv(this.g,[20969472]).then(function(b){b=l(b).next().value;return 0==b.events.size?"":Ou(b.events,a)}):Promise.resolve($fa(this,a))};
var $fa=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return Tl(new Blob),a.V.info("Uploading saved logs for feedback."),Ou(c,b)};h=zv.prototype;
h.onError=function(a){this.L&&(this.L(a),this.N=this.L=null,this.rg(9));this.V.info("Mirroring service error: "+a);this.o()};h.didStart=function(){this.N&&(this.N(),this.N=this.L=null);this.X&&(this.X.end(),this.X=null);this.W=Ku();$i(this.J)?this.wh():aj(this.J)?this.th():dj(this.J)&&this.ui()};h.didStop=function(){this.o()};h.send=function(a){if(this.D){var b=JSON.parse(a.jsonFormatData);nb(this.V,function(){return"Sending message: "+JSON.stringify(b)});this.D.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
h.qt=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.F){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.V.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.F.send(b))}};
var Wfa=function(a,b){a.H=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.M=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.D=bu(b.id);a.D.onMessage=a.qt.bind(a)},Xfa=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.Db.vg.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.Db.we;c.type=b.shouldCaptureVideo&&b.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:b.shouldCaptureVideo?
mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return c},Yfa=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;b=b.Db.tabId||-1;$i(c)?a.j.getMirroringServiceHostForTab(b,mojo.makeRequest(a.l)):aj(c)?a.j.getMirroringServiceHostForDesktop(-1,a.nb,mojo.makeRequest(a.l)):dj(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},Zfa=function(a,b,c){$i(c)&&!chrome.tabs.onUpdated.hasListener(a.ja)&&chrome.tabs.onUpdated.addListener(a.ja);
($i(c)||dj(c))&&jj(a.m,b.Db.tabId)};zv.prototype.xa=function(a,b,c){Zi(14);this.m&&kj(this.m,a,b,c)};
zv.prototype.o=function(){chrome.tabs.onUpdated.removeListener(this.ja);return this.u?this.ea?this.l?(this.l.ptr.reset(),this.F=this.l=null,this.D&&this.D.eb(),this.D=null,this.H&&(this.H.close(),this.H=null),this.M&&(this.M.close(),this.M=null),this.j.oi(this.m.h.id),this.m=null,this.nb=this.J="",this.W&&(this.W.end(),this.W=null),this.uh(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):fj.prototype.o.call(this)};
zv.prototype.Zj=function(a,b,c,d,e,f){return this.u?Bi(Error("Mirroring service does not support updating stream")):fj.prototype.Zj.call(this,a,b,c,d,e,f)};zv.prototype.send=zv.prototype.send;zv.prototype.didStop=zv.prototype.didStop;zv.prototype.didStart=zv.prototype.didStart;zv.prototype.onError=zv.prototype.onError;var aga=new zv;Xi("mr.mirror.cast.Service",aga);
